### ISSUE TITLE
GCD 개선

### ISSUE THREAD

**Issue by rhs0266** [Minseok235/PS_algorithm#1]
https://github.com/Minseok235/PS_algorithm/blob/93c102666e6b1625ec9debb0332ded5bb76058d2/GCD-Euclidian.cpp#L5-L6

a=101, b=2 인 경우에 GCD 함수의 재귀 호출이 어떻게 일어나는 지 직접 확인해보기

(a, b) = (b-a, a) =>? (b%a, a) 여도 되는가?

**Comment by Minseok235** [comment]
good
